ALTER TABLE ingressos DROP CONSTRAINT ck_ingressos_status;

ALTER TABLE ingressos
    ADD CONSTRAINT ck_ingressos_status
        CHECK (status IN ('CONFIRMADO', 'UTILIZADO', 'CANCELADO', 'AVALIADO'));

CREATE TABLE avaliacoes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingresso_id BIGINT    NOT NULL UNIQUE,
    filme_id    BIGINT    NOT NULL,
    sessao_id   BIGINT    NOT NULL,
    usuario_id  BIGINT    NOT NULL,
    nota        INT       NOT NULL,
    comentario  TEXT,
    criado_em   TIMESTAMP NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_avaliacoes_ingresso
        FOREIGN KEY (ingresso_id) REFERENCES ingressos(id),

    CONSTRAINT fk_avaliacoes_filme
        FOREIGN KEY (filme_id) REFERENCES filmes(id),

    CONSTRAINT fk_avaliacoes_sessao
        FOREIGN KEY (sessao_id) REFERENCES sessoes(id),

    CONSTRAINT fk_avaliacoes_usuario
        FOREIGN KEY (usuario_id) REFERENCES users(id),

    CONSTRAINT ck_avaliacoes_nota
        CHECK (nota BETWEEN 1 AND 5)
);

CREATE INDEX idx_avaliacoes_filme_id   ON avaliacoes(filme_id);
CREATE INDEX idx_avaliacoes_sessao_id  ON avaliacoes(sessao_id);
CREATE INDEX idx_avaliacoes_usuario_id ON avaliacoes(usuario_id);
CREATE INDEX idx_avaliacoes_nota       ON avaliacoes(nota);
